title: Envision Lahaina
description: Create a web portal that facilitates the civic engagement around how to rebuild Lahaina, Maui, including surveys, forums, sharing design concepts with visual and data models for economic, environmental, etc. analysis.
google_analytics:
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions